apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  NODE_ENV: "production"
  API_GATEWAY_PORT: "3000"
  USER_SERVICE_PORT: "3001"
  COURSE_SERVICE_PORT: "3002"
  ENROLLMENT_SERVICE_PORT: "3003"
  PAYMENT_SERVICE_PORT: "3004"
  NOTIFICATION_SERVICE_PORT: "3005"
  MEDIA_SERVICE_PORT: "3006"
  REDIS_HOST: "redis-service.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://admin:admin@rabbitmq-service.infra.svc.cluster.local:5672"