apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend
type: Opaque
data:
  # Base64 encoded values - replace with your actual secrets
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2UuaW5mcmEuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9sZWFybmluZ19wbGF0Zm9ybT9zY2hlbWE9cHVibGlj
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
  STRIPE_SECRET_KEY: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5X2hlcmU=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfeW91cl93ZWJob29rX3NlY3JldF9oZXJl
  SMTP_USER: eW91ci1lbWFpbEBnbWFpbC5jb20=
  SMTP_PASS: eW91ci1hcHAtcGFzc3dvcmQ=